---
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    enable-self-preservation: true
    renewalPercentThreshold: 0.1
    
    
#eureka.renewalPercentThreshold: 0.1

